"""pyhoglake — Python client for the hoglake control plane."""

from . import ops, transforms
from .bounds import decode_bound, encode_bound
from .client import (
    UNGUARDED,
    Catalog,
    HoglakeClient,
    Namespace,
    S3Config,
    Table,
    View,
)
from .errors import (
    AlreadyExistsError,
    CommitConflictError,
    ExpiredError,
    HoglakeError,
    IncarnationChangedError,
    MalformedResponseError,
    NotFoundError,
    OffsetRegressionError,
    UnsupportedTypeError,
    ValidationError,
)
from .models import (
    AppendedFile,
    AppendResult,
    CatalogInfo,
    CatalogOptions,
    ChangesPlan,
    CleanupResult,
    Column,
    ColumnStats,
    CommitResult,
    ConsumerOffset,
    DataFile,
    DeleteFile,
    ExpiryResult,
    PartitionField,
    PartitionSpec,
    ScanFile,
    Snapshot,
    SnapshotChange,
    TableInfo,
    TableSummary,
    ViewInfo,
)
from .ops import AlterOp
from .types import arrow_type_to_coltype, coltype_to_arrow

__version__ = "0.1.0"

__all__ = [
    "UNGUARDED",
    "AlreadyExistsError",
    "AlterOp",
    "AppendResult",
    "AppendedFile",
    "Catalog",
    "CatalogInfo",
    "CatalogOptions",
    "ChangesPlan",
    "CleanupResult",
    "Column",
    "ColumnStats",
    "CommitConflictError",
    "CommitResult",
    "ConsumerOffset",
    "DataFile",
    "DeleteFile",
    "ExpiredError",
    "ExpiryResult",
    "HoglakeClient",
    "HoglakeError",
    "IncarnationChangedError",
    "MalformedResponseError",
    "Namespace",
    "NotFoundError",
    "OffsetRegressionError",
    "PartitionField",
    "PartitionSpec",
    "S3Config",
    "ScanFile",
    "Snapshot",
    "SnapshotChange",
    "Table",
    "TableInfo",
    "TableSummary",
    "UnsupportedTypeError",
    "ValidationError",
    "View",
    "ViewInfo",
    "__version__",
    "arrow_type_to_coltype",
    "coltype_to_arrow",
    "decode_bound",
    "encode_bound",
    "ops",
    "transforms",
]
