package com.posthog.hoglake

import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

/**
 * The version resource is generated by Gradle from `project.version`, so
 * this test is really about the wiring: if `generateVersionResource` stops
 * running, or stops landing on the runtime classpath, [BuildInfo] degrades
 * to "unknown" silently and the webui badge quietly lies. That degradation
 * is deliberate — a missing version must not stop the server — which is
 * exactly why it needs a test to notice it.
 *
 * The version STRING is not pinned here: it changes every release, and a
 * test that has to be edited by the release PR is a test that gets edited
 * without being read.
 */
class BuildInfoTest {
    @Test
    fun `the running version comes from the generated resource`() {
        assertThat(BuildInfo.version)
            .isNotBlank()
            .isNotEqualTo(BuildInfo.UNKNOWN)
            // project.version shape: 1.2.3 or 1.2.3-dev between releases.
            .matches("""\d+\.\d+\.\d+(-\w+)?""")
    }
}
