package com.posthog.hoglake

import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

/**
 * The version resource is generated by Gradle from `project.version`, so
 * this test is really about the wiring: if `generateVersionResource` stops
 * running, or stops landing on the runtime classpath, [BuildInfo] degrades
 * to "unknown" silently and the webui badge quietly lies. That degradation
 * is deliberate — a missing version must not stop the server — which is
 * exactly why it needs a test to notice it.
 *
 * The version STRING is not pinned here: it changes every release, and a
 * test that has to be edited by the release PR is a test that gets edited
 * without being read.
 */
class BuildInfoTest {
    @Test
    fun `an unstamped build reports no build stamp`() {
        // The default, and the one that must not regress into a sentinel:
        // an ordinary gradle build passes no -PbuildStamp, and absent has
        // to stay absent so the webui shows a bare version rather than
        // something that reads like a broken deploy.
        assertThat(BuildInfo.buildStamp).isNull()
    }

    @Test
    fun `a supplied stamp is accepted as-is`() {
        assertThat(BuildInfo.sanitizeStamp("20260915T2104Z")).isEqualTo("20260915T2104Z")
        assertThat(BuildInfo.sanitizeStamp("1.2.3-rc4+g0ab1cd")).isEqualTo("1.2.3-rc4+g0ab1cd")
    }

    @Test
    fun `blank and missing are no stamp, not a fault`() {
        assertThat(BuildInfo.sanitizeStamp(null)).isNull()
        assertThat(BuildInfo.sanitizeStamp("")).isNull()
        assertThat(BuildInfo.sanitizeStamp("   ")).isNull()
    }

    @Test
    fun `a malformed stamp costs the badge, not the endpoint`() {
        // It arrives through a Docker build arg and lands in every
        // /v1/info response, so a pipeline that sets it wrong must not be
        // able to put an unbounded or control-laden blob on a hot path.
        assertThat(BuildInfo.sanitizeStamp("a".repeat(65))).isNull()
        assertThat(BuildInfo.sanitizeStamp("has space")).isNull()
        assertThat(BuildInfo.sanitizeStamp("new\nline")).isNull()
        assertThat(BuildInfo.sanitizeStamp("<script>alert(1)</script>")).isNull()
        assertThat(BuildInfo.sanitizeStamp("-leading-punctuation")).isNull()
        // The boundary itself is legal: 64 characters exactly.
        assertThat(BuildInfo.sanitizeStamp("b".repeat(64))).isEqualTo("b".repeat(64))
    }

    @Test
    fun `the running version comes from the generated resource`() {
        assertThat(BuildInfo.version)
            .isNotBlank()
            .isNotEqualTo(BuildInfo.UNKNOWN)
            // project.version shape: 1.2.3 or 1.2.3-dev between releases.
            .matches("""\d+\.\d+\.\d+(-\w+)?""")
    }
}
